services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    environment:
      LT_LOAD_ONLY: "zh,nl,en"
      LT_DISABLE_WEB_UI: "true"
    ports:
      - "192.168.10.5:5000:5000"
    networks:
      - hassio

networks:
  hassio:
    external: true
